# -*- coding: utf-8 -*-
"""ProyectoAlgebra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xyHuS8NzOfVcP-LUXtw_DJT-W9dRtbUl
"""

import math
import pandas as pd
import matplotlib.pyplot as plt
import gradio as gr

ETIQUETA_PESO = "Peso NFR (W)"
COL_NOMBRE = "Requisito"


# ---------------------------------------------------------------------------
# LÓGICA DEL MÉTODO IPA
# ---------------------------------------------------------------------------
def normalizar_vector(v):
    total = sum(v)
    if total == 0:
        raise ValueError("La suma del vector de pesos no puede ser 0.")
    return [x / total for x in v]


def media_geometrica_ponderada(fila, pesos):
    ln_R = sum(w * math.log(d) for d, w in zip(fila, pesos) if d > 0)
    return math.exp(ln_R)


def calcular_prioridades(matriz_D, pesos_NFR, nombres_FR):
    NW = normalizar_vector(pesos_NFR)
    R = [media_geometrica_ponderada(fila, NW) for fila in matriz_D]
    NR = normalizar_vector(R)
    ranking = sorted(zip(nombres_FR, NR), key=lambda p: p[1], reverse=True)
    return NW, R, NR, ranking


# ---------------------------------------------------------------------------
# GENERAR TABLA DINÁMICA
# ---------------------------------------------------------------------------
def generar_tabla(num_fr, num_nfr, nombres_fr_txt, nombres_nfr_txt):
    num_fr, num_nfr = int(num_fr), int(num_nfr)

    fr_list = [n.strip() for n in nombres_fr_txt.split(",") if n.strip()]
    nfr_list = [n.strip() for n in nombres_nfr_txt.split(",") if n.strip()]

    # Completar o recortar nombres según el tamaño elegido
    fr_list = (fr_list + [f"FR{i+1}" for i in range(num_fr)])[:num_fr]
    nfr_list = (nfr_list + [f"NFR{j+1}" for j in range(num_nfr)])[:num_nfr]

    columnas = [COL_NOMBRE] + nfr_list
    filas = []
    for nombre in fr_list:
        filas.append([nombre] + [5] * num_nfr)          # valores por defecto
    filas.append([ETIQUETA_PESO] + [5] * num_nfr)        # fila de pesos W

    df = pd.DataFrame(filas, columns=columnas)
    return df


# ---------------------------------------------------------------------------
# CALCULAR Y GRAFICAR RANKING
# ---------------------------------------------------------------------------
def calcular(df: pd.DataFrame):
    try:
        df = df.copy()
        nombres_col = df.columns[0]

        fila_pesos = df[df[nombres_col] == ETIQUETA_PESO]
        filas_fr = df[df[nombres_col] != ETIQUETA_PESO]

        if fila_pesos.empty or filas_fr.empty:
            raise ValueError(f"La tabla debe tener una fila llamada '{ETIQUETA_PESO}' y al menos un FR.")

        nfr_cols = df.columns[1:]
        pesos_NFR = [float(v) for v in fila_pesos[nfr_cols].iloc[0]]
        nombres_FR = filas_fr[nombres_col].tolist()
        matriz_D = filas_fr[nfr_cols].astype(float).values.tolist()

        NW, R, NR, ranking = calcular_prioridades(matriz_D, pesos_NFR, nombres_FR)

        # --- Gráfico de barras horizontal con el ranking ---
        nombres_rank = [r[0] for r in ranking]
        valores_rank = [r[1] for r in ranking]

        fig, ax = plt.subplots(figsize=(6, 0.6 * len(nombres_rank) + 1))
        colores = plt.cm.Purples([0.9 - 0.5 * (i / max(1, len(nombres_rank) - 1)) for i in range(len(nombres_rank))])
        ax.barh(nombres_rank[::-1], valores_rank[::-1], color=colores[::-1])
        ax.set_xlabel("Prioridad normalizada (NR)")
        ax.set_title("Ranking de requisitos funcionales")
        for i, v in enumerate(valores_rank[::-1]):
            ax.text(v, i, f" {v*100:.1f}%", va="center", fontsize=9)
        fig.tight_layout()

        resumen_nw = " · ".join(f"{n}={w*100:.0f}%" for n, w in zip(nfr_cols, NW))
        texto = f"**Pesos normalizados de los NFR:** {resumen_nw}"

        tabla_resultado = pd.DataFrame({
            "Requisito Funcional": [r[0] for r in ranking],
            "Prioridad (NR)": [f"{r[1]*100:.2f}%" for r in ranking],
        })

        return fig, texto, tabla_resultado

    except Exception as e:
        raise gr.Error(f"Error al calcular: {e}")


# ---------------------------------------------------------------------------
# INTERFAZ GRADIO
# ---------------------------------------------------------------------------
with gr.Blocks(title="IPA Simplificado") as demo:
    gr.Markdown("## IPA Simplificado — Priorización de Requisitos")
    gr.Markdown(
        "Ajusta el número de requisitos, edita la matriz de importancia "
        "(escala sugerida 1-9) y la fila de pesos, y calcula el ranking en vivo."
    )

    with gr.Row():
        num_fr = gr.Slider(1, 8, value=4, step=1, label="N° de requisitos funcionales (FR)")
        num_nfr = gr.Slider(1, 6, value=3, step=1, label="N° de requisitos no funcionales (NFR)")

    with gr.Row():
        nombres_fr = gr.Textbox(
            value="Login,Reportes,Pagos,Notificaciones",
            label="Nombres de los FR (separados por coma)",
        )
        nombres_nfr = gr.Textbox(
            value="Seguridad,Usabilidad,Rendimiento",
            label="Nombres de los NFR (separados por coma)",
        )

    btn_generar = gr.Button("Generar tabla")

    tabla = gr.Dataframe(
        value=generar_tabla(4, 3, "Login,Reportes,Pagos,Notificaciones", "Seguridad,Usabilidad,Rendimiento"),
        interactive=True,
        label="Matriz de decisión D (última fila = pesos W de cada NFR)",
    )

    btn_calcular = gr.Button("Calcular prioridades", variant="primary")

    resumen = gr.Markdown()
    grafico = gr.Plot(label="Ranking")
    tabla_final = gr.Dataframe(label="Detalle del ranking", interactive=False)

    btn_generar.click(
        fn=generar_tabla,
        inputs=[num_fr, num_nfr, nombres_fr, nombres_nfr],
        outputs=tabla,
    )
    btn_calcular.click(fn=calcular, inputs=tabla, outputs=[grafico, resumen, tabla_final])


if __name__ == "__main__":
    demo.launch()

